### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin123@test.com",
    "password": "admin123"
}

### Sign in a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "asddasd@test.com",
    "password": "admin123"
}

### Get the current user
GET http://localhost:3000/auth/whoami

### Sign out a user
POST http://localhost:3000/auth/signout

### Find a user with a given id
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=facu@test.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/2

### Update a user with a given id
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "facu@test.com"
}